-- MySQL Script generated by MySQL Workbench
-- sáb 15 dic 2018 10:07:36 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemaUDL
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistemaUDL` ;

-- -----------------------------------------------------
-- Schema sistemaUDL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaUDL` DEFAULT CHARACTER SET utf8 ;
USE `sistemaUDL` ;

-- -----------------------------------------------------
-- Table `sistemaUDL`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Alumno` (
  `id_Alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre_Alumno` VARCHAR(45) NOT NULL,
  `apaterno_Alumno` VARCHAR(45) NOT NULL,
  `amaterno_Alumno` VARCHAR(45) NOT NULL,
  `fhnacimiento_Alumno` VARCHAR(45) NOT NULL,
  `direccion_Alumno` VARCHAR(45) NOT NULL,
  `curp_Alumno` VARCHAR(45) NOT NULL,
  `rfc_Alumno` VARCHAR(45) NULL,
  `telefono_Alumno` DECIMAL(10,0) NOT NULL,
  `fhalta_Alumno` DATETIME GENERATED ALWAYS AS (select now();) VIRTUAL,
  `Usuario_id_Usuario` INT NOT NULL,
  `Carrera_id_Carrera` INT NOT NULL,
  PRIMARY KEY (`id_Alumno`, `Usuario_id_Usuario`, `Carrera_id_Carrera`),
  CONSTRAINT `fk_Alumno_Usuario1`
    FOREIGN KEY (`Usuario_id_Usuario`)
    REFERENCES `sistemaUDL`.`Usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Carrera1`
    FOREIGN KEY (`Carrera_id_Carrera`)
    REFERENCES `sistemaUDL`.`Carrera` (`id_Carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Alumno_Usuario1_idx` ON `sistemaUDL`.`Alumno` (`Usuario_id_Usuario` ASC) VISIBLE;

CREATE INDEX `fk_Alumno_Carrera1_idx` ON `sistemaUDL`.`Alumno` (`Carrera_id_Carrera` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Calificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Calificacion` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Calificacion` (
  `id_Calificacion` INT NOT NULL AUTO_INCREMENT,
  `Oportunidad_id_Oportunidad` INT NOT NULL,
  `Oportunidad_Examen_id_Examen` INT NOT NULL,
  `Oportunidad_Examen_Materia_id_Materia` INT NOT NULL,
  `Calificacion` DECIMAL(4,2) NULL,
  PRIMARY KEY (`id_Calificacion`, `Oportunidad_id_Oportunidad`, `Oportunidad_Examen_id_Examen`, `Oportunidad_Examen_Materia_id_Materia`),
  CONSTRAINT `fk_Calificacion_Oportunidad1`
    FOREIGN KEY (`Oportunidad_id_Oportunidad` , `Oportunidad_Examen_id_Examen` , `Oportunidad_Examen_Materia_id_Materia`)
    REFERENCES `sistemaUDL`.`Oportunidad` (`id_Oportunidad` , `Examen_id_Examen` , `Examen_Materia_id_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Calificacion_Oportunidad1_idx` ON `sistemaUDL`.`Calificacion` (`Oportunidad_id_Oportunidad` ASC, `Oportunidad_Examen_id_Examen` ASC, `Oportunidad_Examen_Materia_id_Materia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Carrera` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Carrera` (
  `id_Carrera` INT NOT NULL AUTO_INCREMENT,
  `nombre_Carrera` VARCHAR(45) NOT NULL,
  `fhalta_Carrera` DATETIME NULL DEFAULT select now();,
  PRIMARY KEY (`id_Carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Carrera_has_Semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Carrera_has_Semestre` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Carrera_has_Semestre` (
  `Carrera_id_Carrera` INT NOT NULL,
  `Semestre_id_Semestre` INT NOT NULL,
  PRIMARY KEY (`Carrera_id_Carrera`, `Semestre_id_Semestre`),
  CONSTRAINT `fk_Carrera_has_Semestre_Carrera1`
    FOREIGN KEY (`Carrera_id_Carrera`)
    REFERENCES `sistemaUDL`.`Carrera` (`id_Carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrera_has_Semestre_Semestre1`
    FOREIGN KEY (`Semestre_id_Semestre`)
    REFERENCES `sistemaUDL`.`Semestre` (`id_Semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Carrera_has_Semestre_Semestre1_idx` ON `sistemaUDL`.`Carrera_has_Semestre` (`Semestre_id_Semestre` ASC) VISIBLE;

CREATE INDEX `fk_Carrera_has_Semestre_Carrera1_idx` ON `sistemaUDL`.`Carrera_has_Semestre` (`Carrera_id_Carrera` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Examen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Examen` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Examen` (
  `id_Examen` INT NOT NULL AUTO_INCREMENT,
  `descripcion_Examen` VARCHAR(45) NULL,
  `Materia_id_Materia` INT NOT NULL,
  PRIMARY KEY (`id_Examen`, `Materia_id_Materia`),
  CONSTRAINT `fk_Examen_Materia1`
    FOREIGN KEY (`Materia_id_Materia`)
    REFERENCES `sistemaUDL`.`Materia` (`id_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Examen_Materia1_idx` ON `sistemaUDL`.`Examen` (`Materia_id_Materia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Materia` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Materia` (
  `id_Materia` INT NOT NULL AUTO_INCREMENT,
  `nombre_Materia` VARCHAR(45) NOT NULL,
  `salon_Materia` VARCHAR(45) NOT NULL,
  `fhalta_Materia` VARCHAR(45) GENERATED ALWAYS AS (select now();),
  PRIMARY KEY (`id_Materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Oportunidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Oportunidad` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Oportunidad` (
  `id_Oportunidad` INT NOT NULL,
  `descripcion_Oportunidad` VARCHAR(45) NULL,
  `Examen_id_Examen` INT NOT NULL,
  `Examen_Materia_id_Materia` INT NOT NULL,
  PRIMARY KEY (`id_Oportunidad`, `Examen_id_Examen`, `Examen_Materia_id_Materia`),
  CONSTRAINT `fk_Oportunidad_Examen1`
    FOREIGN KEY (`Examen_id_Examen` , `Examen_Materia_id_Materia`)
    REFERENCES `sistemaUDL`.`Examen` (`id_Examen` , `Materia_id_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Oportunidad_Examen1_idx` ON `sistemaUDL`.`Oportunidad` (`Examen_id_Examen` ASC, `Examen_Materia_id_Materia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Pagina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Pagina` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Pagina` (
  `id_Pagina` INT NOT NULL AUTO_INCREMENT,
  `descripcion_Pagina` VARCHAR(45) NOT NULL,
  `nombre_Pagina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Pagina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Pagina_has_Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Pagina_has_Rol` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Pagina_has_Rol` (
  `Pagina_id_Pagina` INT NOT NULL,
  `Rol_id_Rol` INT NOT NULL,
  PRIMARY KEY (`Pagina_id_Pagina`, `Rol_id_Rol`),
  CONSTRAINT `fk_Pagina_has_Rol_Pagina1`
    FOREIGN KEY (`Pagina_id_Pagina`)
    REFERENCES `sistemaUDL`.`Pagina` (`id_Pagina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagina_has_Rol_Rol1`
    FOREIGN KEY (`Rol_id_Rol`)
    REFERENCES `sistemaUDL`.`Rol` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pagina_has_Rol_Rol1_idx` ON `sistemaUDL`.`Pagina_has_Rol` (`Rol_id_Rol` ASC) VISIBLE;

CREATE INDEX `fk_Pagina_has_Rol_Pagina1_idx` ON `sistemaUDL`.`Pagina_has_Rol` (`Pagina_id_Pagina` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Rol` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Rol` (
  `id_Rol` INT NOT NULL AUTO_INCREMENT,
  `descripcion_Rol` VARCHAR(45) NOT NULL,
  `fhalta_Rol` DATETIME NOT NULL DEFAULT select now();,
  PRIMARY KEY (`id_Rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Semestre` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Semestre` (
  `id_Semestre` INT NOT NULL AUTO_INCREMENT,
  `numero_Semestre` INT NOT NULL,
  `fhalta_Semestre` DATETIME GENERATED ALWAYS AS (select now();),
  PRIMARY KEY (`id_Semestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Semestre_has_Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Semestre_has_Materia` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Semestre_has_Materia` (
  `Semestre_id_Semestre` INT NOT NULL,
  `Materia_id_Materia` INT NOT NULL,
  PRIMARY KEY (`Semestre_id_Semestre`, `Materia_id_Materia`),
  CONSTRAINT `fk_Semestre_has_Materia_Semestre1`
    FOREIGN KEY (`Semestre_id_Semestre`)
    REFERENCES `sistemaUDL`.`Semestre` (`id_Semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Semestre_has_Materia_Materia1`
    FOREIGN KEY (`Materia_id_Materia`)
    REFERENCES `sistemaUDL`.`Materia` (`id_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Semestre_has_Materia_Materia1_idx` ON `sistemaUDL`.`Semestre_has_Materia` (`Materia_id_Materia` ASC) VISIBLE;

CREATE INDEX `fk_Semestre_has_Materia_Semestre1_idx` ON `sistemaUDL`.`Semestre_has_Materia` (`Semestre_id_Semestre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemaUDL`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemaUDL`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `sistemaUDL`.`Usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `codigo_Usuario` VARCHAR(45) NOT NULL,
  `password_Usuario` VARCHAR(45) NOT NULL,
  `estatus_Usuario` VARCHAR(45) NOT NULL,
  `fhalta_Usuario` DATETIME GENERATED ALWAYS AS (select now();),
  `Rol_id_Rol` INT NOT NULL,
  PRIMARY KEY (`id_Usuario`, `Rol_id_Rol`),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_id_Rol`)
    REFERENCES `sistemaUDL`.`Rol` (`id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Rol1_idx` ON `sistemaUDL`.`Usuario` (`Rol_id_Rol` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
